import { Inter, Lato,Bebas_Neue } from "next/font/google";
import "../../../app/globals.css";
import Layout from "@/app/components/modules/Layout";

const inter = Inter({ subsets: ["latin"] });
export const lato = Lato({ subsets: ["latin"], weight: ["400", "700", "900"] }); // You can specify weights if needed
export const bebasNeue = Bebas_Neue({ subsets: ["latin"], weight: ["400"] }); // Bebas Neue only has 400 weight
export const metadata = {
  title: "BlogPage",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` ${lato.className} `}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
