"use client"
import { Inter, Lato } from "next/font/google";
import "../../../app/globals.css";
import Tostify from "@/app/components/constants/Elements/Tostify";
import ToasterContainerSnackbar from "@/app/components/constants/Elements/Tostify";
// import Layout from "@/app/components/modules/Layout";

const inter = Inter({ subsets: ["latin"] });
const lato = Lato({ subsets: ["latin"], weight: ["400", "700", "900"] }); // You can specify weights if needed

// export const metadata = {
//   title: "BlogPage",
//   description: "Generated by create next app",
// };

export default function AuthenticationLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${lato.className}`}>
        <ToasterContainerSnackbar>{children}</ToasterContainerSnackbar>
      </body>
    </html>
  );
}
